// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import { initFormatters } from './formatters'
import type { Locales, Translations } from './i18n-types'
import { loadedFormatters, loadedLocales, locales } from './i18n-util'

import en from './en'
import es from './es'
import fr from './fr'
import ja from './ja'
import ko from './ko'
import pt from './pt'
import zh_CN from './zh-CN'
import zh_HK from './zh-HK'
import zh_TW from './zh-TW'

const localeTranslations = {
	en,
	es,
	fr,
	ja,
	ko,
	pt,
	'zh-CN': zh_CN,
	'zh-HK': zh_HK,
	'zh-TW': zh_TW,
}

export const loadLocale = (locale: Locales): void => {
	if (loadedLocales[locale]) return

	loadedLocales[locale] = localeTranslations[locale] as unknown as Translations
	loadFormatters(locale)
}

export const loadAllLocales = (): void => locales.forEach(loadLocale)

export const loadFormatters = (locale: Locales): void =>
	void (loadedFormatters[locale] = initFormatters(locale))
